# .github/release.yml

changelog:
  categories:
    - title: 🏕 Features
      labels:
        - enhancement
      exclude:
        labels:
          - dependencies
    - title: 👒 Bugfixes
      labels:
        - bug
