[project]
name = "Anker-Solix-Api"
version = "1.4.0"
description = "Python library for Anker Solix Power devices (Solarbank, Inverter etc)"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/thomluther/anker-solix-api"
"Bug Tracker" = "https://github.com/thomluther/anker-solix-api/issues"
"Discussions" = "https://github.com/thomluther/anker-solix-api/discussions"

[tool.isort]
profile="black"

[tool.pylint]
jobs=0
disable = ["import-error", "line-too-long", "invalid-name"]
